plugins {
    id 'java-library'
    id 'jacoco'
    id 'com.github.spotbugs' version '6.0.9'
}

group = 'com.misrilibrary'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

import com.github.spotbugs.snom.Effort
import com.github.spotbugs.snom.Confidence

spotbugs {
    effort = Effort.valueOf('MAX')
    reportLevel = Confidence.valueOf('MEDIUM')
}

spotbugsMain {
    reports {
        html.required = true
        xml.required = false
    }
}

spotbugsTest.enabled = false
